version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ageng
      PSOTGRES_DB: db_sistem_gudang
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    # environment:
    #   DATABASE_URL: "postgresql://postgres:ageng@postgres:5432/db_sistem_gudang"
    command: npm run dev

volumes:
  postgres_data:
